version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  service2:
    build: ./service2
    ports:
      - "5000:80"

  service3:
    build: ./service3
    ports:
      - "8000:80"
    env_file:
      - .env

volumes:
  redis_data:
